env = {"parser":None,
       "tokens":[],
       "files":[],
       "lexer":None,
       "base_dir":"",
       "debug":False,
       "quiet":False,
       "minify":False,
       "minify_command":None,
       "define":{}}